//
// (c) 2009-13 ClinRisk Ltd.
// All rights reserved.
//
// No unauthorised copying, distribution, modification, creating derived works, 
// or even compilation allowed, unless express permission has been granted by 
// ClinRisk Ltd.
//

using System;
using System.Collections.Generic;
using System.Text;

using CRStandardDefinitions;
using ClinRiskAutogenerated;

namespace bmiPredictor
{
    public class BmiPredictor
    {
        public static BmiPredictorResults estimate(Gender sex,int age,bool b_cvd,bool b_treatedhyp,DiabetesCat diabetes_cat,Ethnicity ethnicity,SmokeCat smoke_cat)
        {
            BmiPredictorResults results = new BmiPredictorResults();
            double score;
            if (sex == Gender.Female)
            {
                score = z3_bmi_predictor_0_2013.bmi_female(age, b_cvd, b_treatedhyp, diabetes_cat, ethnicity, smoke_cat);
            }
            else
            {
                score = z3_bmi_predictor_1_2013.bmi_male(age, b_cvd, b_treatedhyp, diabetes_cat, ethnicity, smoke_cat);
            }
            results.bmi = ((int)(score * 10 + 0.5)) / 10.0;
            return results;
        }

        public static String version()
        {
            return "bmiPredictor v. 2013.0";
        }
    }
}
