//
// (c) 2010-13 ClinRisk Ltd.
// All rights reserved.
//
// No unauthorised copying, distribution, modification, creating derived works, 
// or even compilation allowed, unless express permission has been granted by 
// ClinRisk Ltd.
//

using System;
using System.Collections.Generic;
using System.Text;

using CRStandardDefinitions;
using ClinRiskAutogenerated;

namespace cholRatioPredictor
{
    public class CholRatioPredictor
    {
        public static CholRatioPredictorResults estimate(Gender sex,int age,bool b_cvd,bool b_treatedhyp,DiabetesCat diabetes_cat,Ethnicity ethnicity,SmokeCat smoke_cat)
        {
            CholRatioPredictorResults results = new CholRatioPredictorResults();
            double score;
            if (sex == Gender.Female)
            {
                score = z3_ratio_predictor_0_2013.ratio_female(age, b_cvd, b_treatedhyp, diabetes_cat, ethnicity, smoke_cat);
            }
            else
            {
                score = z3_ratio_predictor_1_2013.ratio_male(age, b_cvd, b_treatedhyp, diabetes_cat, ethnicity, smoke_cat);
            }
            results.cholRatio = ((int)(score * 10 + 0.5)) / 10.0;
            return results;
        }

        public static String version()
        {
            return "cholRatioPredictor v. 2013.0";
        }

    }
}
