/* 
 * (c) 2013 ClinRisk Ltd.  All rights reserved.
 * This file has been auto-generated.
 * XML source: Q104_model_53_0.xml
 * STATA dta time stamp: 8 Mar 2017 19:45
 * .NET file create date: Thu 26 Oct 2017 10:51:51 BST
 */

using System;
using System.IO;
using System.Collections;

using CRStandardDefinitions;

namespace ClinRiskAutogenerated 
{
	public class Q104_model_53_0 {
		/* cvd */

		static private double cvd_female_raw(
			int age,int b_AF,int b_atypicalantipsy,int b_corticosteroids,int b_migraine,int b_ra,int b_renal,int b_semi,int b_sle,int b_treatedhyp,int b_type1,int b_type2,double bmi,int ethrisk,int fh_cvd,double rati,double sbp,double sbps5,int smoke_cat,int surv,double town
		)
		{
			double[] survivor = {
				0,
				0.999091982841492,
				0.998137593269348,
				0.997148871421814,
				0.996084153652191,
				0.994926750659943,
				0.993812143802643,
				0.992674827575684,
				0.991466045379639,
				0.990171313285828,
				0.988876402378082,
				0.987446784973145,
				0.985951066017151,
				0.984341323375702,
				0.982662975788116,
				0.980810165405273
			};

			/* The conditional arrays */

			double[] Iethrisk = {
				0,
				0,
				0.2804031433299542500000000,
				0.5629899414207539800000000,
				0.2959000085111651600000000,
				0.0727853798779825450000000,
				-0.1707213550885731700000000,
				-0.3937104331487497100000000,
				-0.3263249528353027200000000,
				-0.1712705688324178400000000
			};
			double[] Ismoke = {
				0,
				0.1338683378654626200000000,
				0.5620085801243853700000000,
				0.6674959337750254700000000,
				0.8494817764483084700000000
			};

			/* Applying the fractional polynomial transforms */
			/* (which includes scaling)                      */

			double dage = age;
			dage=dage/10;
			double age_1 = Math.Pow(dage,-2);
			double age_2 = dage;
			double dbmi = bmi;
			dbmi=dbmi/10;
			double bmi_1 = Math.Pow(dbmi,-2);
			double bmi_2 = Math.Pow(dbmi,-2)*Math.Log(dbmi);

			/* The normalisation coefficients */

			double mage_1 = 0.053274843841791;
			double mage_2 = 4.332503318786621;
			double mbmi_1 = 0.154946178197861;
			double mbmi_2 = 0.144462317228317;
			double mrati = 3.476326465606690;
			double msbp = 123.130012512207030;
			double msbps5 = 9.002537727355957;
			double mtown = 0.392308831214905;

			/* Centring the continuous variables */

			age_1 = age_1 - mage_1;
			age_2 = age_2 - mage_2;
			bmi_1 = bmi_1 - mbmi_1;
			bmi_2 = bmi_2 - mbmi_2;
			rati = rati - mrati;
			sbp = sbp - msbp;
			sbps5 = sbps5 - msbps5;
			town = town - mtown;

			/* Start of Sum */
			double a=0;

			/* The conditional sums */

			a += Iethrisk[ethrisk];
			a += Ismoke[smoke_cat];

			/* The continuous coefficients */

			double cage_1 = -8.1388109247726188000000000;
			double cage_2 = 0.7973337668969909800000000;
			double cbmi_1 = 0.2923609227546005200000000;
			double cbmi_2 = -4.1513300213837665000000000;
			double crati = 0.1533803582080255400000000;
			double csbp = 0.0131314884071034240000000;
			double csbps5 = 0.0078894541014586095000000;
			double ctown = 0.0772237905885901080000000;

			/* Sum from continuous values */

			a += age_1 * cage_1;
			a += age_2 * cage_2;
			a += bmi_1 * cbmi_1;
			a += bmi_2 * cbmi_2;
			a += rati * crati;
			a += sbp * csbp;
			a += sbps5 * csbps5;
			a += town * ctown;

			/* The boolean coefficients */

			double cb_AF = 1.5923354969269663000000000;
			double cb_atypicalantipsy = 0.2523764207011555700000000;
			double cb_corticosteroids = 0.5952072530460185100000000;
			double cb_migraine = 0.3012672608703450000000000;
			double cb_ra = 0.2136480343518194200000000;
			double cb_renal = 0.6519456949384583300000000;
			double cb_semi = 0.1255530805882017800000000;
			double cb_sle = 0.7588093865426769300000000;
			double cb_treatedhyp = 0.5093159368342300400000000;
			double cb_type1 = 1.7267977510537347000000000;
			double cb_type2 = 1.0688773244615468000000000;
			double cfh_cvd = 0.4544531902089621300000000;

			/* Sum from boolean values */

			a += b_AF * cb_AF;
			a += b_atypicalantipsy * cb_atypicalantipsy;
			a += b_corticosteroids * cb_corticosteroids;
			a += b_migraine * cb_migraine;
			a += b_ra * cb_ra;
			a += b_renal * cb_renal;
			a += b_semi * cb_semi;
			a += b_sle * cb_sle;
			a += b_treatedhyp * cb_treatedhyp;
			a += b_type1 * cb_type1;
			a += b_type2 * cb_type2;
			a += fh_cvd * cfh_cvd;

			/* The interaction coefficients */

			double cage_1_Ismoke1 = -4.7057161785851891000000000;
			double cage_1_Ismoke2 = -2.7430383403573337000000000;
			double cage_1_Ismoke3 = -0.8660808882939218200000000;
			double cage_1_Ismoke4 = 0.9024156236971064800000000;
			double cage_1_b_AF = 19.9380348895465610000000000;
			double cage_1_b_corticosteroids = -0.9840804523593628100000000;
			double cage_1_b_migraine = 1.7634979587872999000000000;
			double cage_1_b_renal = -3.5874047731694114000000000;
			double cage_1_b_sle = 19.6903037386382920000000000;
			double cage_1_b_treatedhyp = 11.8728097339218120000000000;
			double cage_1_b_type1 = -1.2444332714320747000000000;
			double cage_1_b_type2 = 6.8652342000009599000000000;
			double cage_1_bmi_1 = 23.8026234121417420000000000;
			double cage_1_bmi_2 = -71.1849476920870070000000000;
			double cage_1_fh_cvd = 0.9946780794043512700000000;
			double cage_1_sbp = 0.0341318423386154850000000;
			double cage_1_town = -1.0301180802035639000000000;
			double cage_2_Ismoke1 = -0.0755892446431930260000000;
			double cage_2_Ismoke2 = -0.1195119287486707400000000;
			double cage_2_Ismoke3 = -0.1036630639757192300000000;
			double cage_2_Ismoke4 = -0.1399185359171838900000000;
			double cage_2_b_AF = -0.0761826510111625050000000;
			double cage_2_b_corticosteroids = -0.1200536494674247200000000;
			double cage_2_b_migraine = -0.0655869178986998590000000;
			double cage_2_b_renal = -0.2268887308644250700000000;
			double cage_2_b_sle = 0.0773479496790162730000000;
			double cage_2_b_treatedhyp = 0.0009685782358817443600000;
			double cage_2_b_type1 = -0.2872406462448894900000000;
			double cage_2_b_type2 = -0.0971122525906954890000000;
			double cage_2_bmi_1 = 0.5236995893366442900000000;
			double cage_2_bmi_2 = 0.0457441901223237590000000;
			double cage_2_fh_cvd = -0.0768850516984230380000000;
			double cage_2_sbp = -0.0015082501423272358000000;
			double cage_2_town = -0.0315934146749623290000000;

			/* Sum from interaction terms */

			a += age_1 * Utilities.boolToInt((smoke_cat==1)) * cage_1_Ismoke1;
			a += age_1 * Utilities.boolToInt((smoke_cat==2)) * cage_1_Ismoke2;
			a += age_1 * Utilities.boolToInt((smoke_cat==3)) * cage_1_Ismoke3;
			a += age_1 * Utilities.boolToInt((smoke_cat==4)) * cage_1_Ismoke4;
			a += age_1 * b_AF * cage_1_b_AF;
			a += age_1 * b_corticosteroids * cage_1_b_corticosteroids;
			a += age_1 * b_migraine * cage_1_b_migraine;
			a += age_1 * b_renal * cage_1_b_renal;
			a += age_1 * b_sle * cage_1_b_sle;
			a += age_1* b_treatedhyp * cage_1_b_treatedhyp;
			a += age_1 * b_type1 * cage_1_b_type1;
			a += age_1 * b_type2 * cage_1_b_type2;
			a += age_1 * bmi_1 * cage_1_bmi_1;
			a += age_1 * bmi_2 * cage_1_bmi_2;
			a += age_1 * fh_cvd * cage_1_fh_cvd;
			a += age_1 * sbp * cage_1_sbp;
			a += age_1 * town * cage_1_town;
			a += age_2 * Utilities.boolToInt((smoke_cat==1)) * cage_2_Ismoke1;
			a += age_2 * Utilities.boolToInt((smoke_cat==2)) * cage_2_Ismoke2;
			a += age_2 * Utilities.boolToInt((smoke_cat==3)) * cage_2_Ismoke3;
			a += age_2 * Utilities.boolToInt((smoke_cat==4)) * cage_2_Ismoke4;
			a += age_2 * b_AF * cage_2_b_AF;
			a += age_2 * b_corticosteroids * cage_2_b_corticosteroids;
			a += age_2 * b_migraine * cage_2_b_migraine;
			a += age_2 * b_renal * cage_2_b_renal;
			a += age_2 * b_sle * cage_2_b_sle;
			a += age_2* b_treatedhyp * cage_2_b_treatedhyp;
			a += age_2 * b_type1 * cage_2_b_type1;
			a += age_2 * b_type2 * cage_2_b_type2;
			a += age_2 * bmi_1 * cage_2_bmi_1;
			a += age_2 * bmi_2 * cage_2_bmi_2;
			a += age_2 * fh_cvd * cage_2_fh_cvd;
			a += age_2 * sbp * cage_2_sbp;
			a += age_2 * town * cage_2_town;

			/* Calculate the score itself */
			double score = 100.0 * (1 - Math.Pow(survivor[surv], Math.Exp(a)) );
			return score;
		}

		static public Double cvd_female(
			int age,bool b_AF,bool b_atypicalantipsy,bool b_corticosteroids,bool b_migraine,bool b_ra,bool b_renal,bool b_semi,bool b_sle,bool b_treatedhyp,DiabetesCat diabetes_cat,double bmi,Ethnicity ethnicity,bool fh_cvd,double rati,double sbp,double sbps5,SmokeCat smoke_cat,int surv,double town
		)
		{
			Double score;
			double tmp = cvd_female_raw(
				age,	// age must lie in range (25 .. 84)
				Utilities.boolToInt(b_AF),
				Utilities.boolToInt(b_atypicalantipsy),
				Utilities.boolToInt(b_corticosteroids),
				Utilities.boolToInt(b_migraine),
				Utilities.boolToInt(b_ra),
				Utilities.boolToInt(b_renal),
				Utilities.boolToInt(b_semi),
				Utilities.boolToInt(b_sle),
				Utilities.boolToInt(b_treatedhyp),
				Utilities.diabetescatToType1(diabetes_cat),
				Utilities.diabetescatToType2(diabetes_cat),
				bmi,	// bmi must lie in range (18 .. 47)
				Utilities.ethnicityToEthrisk(ethnicity),
				Utilities.boolToInt(fh_cvd),
				rati,	// rati must lie in range (1 .. 12)
				sbp,	// sbp must lie in range (70 .. 250)
				sbps5,	// sbps5 must lie in range (0 .. 40)
				Utilities.smokecatToInt(smoke_cat),
				surv,	// surv must lie in range (1 .. 10)
				town	// town must lie in range (-8 .. 11)
			);
			tmp = Math.Round(tmp*1000000.0)/1000000.0;
			score = tmp;

			return score;
		}

		/* End of cvd */

	}
}
