/* 
 * (c) 2013 ClinRisk Ltd.  All rights reserved.
 * This file has been auto-generated.
 * XML source: Q104_model_53_1.xml
 * STATA dta time stamp: 8 Mar 2017 19:45
 * .NET file create date: Thu 26 Oct 2017 10:52:16 BST
 */

using System;
using System.IO;
using System.Collections;

using CRStandardDefinitions;

namespace ClinRiskAutogenerated 
{
	public class Q104_model_53_1 {
		/* cvd */

		static private double cvd_male_raw(
			int age,int b_AF,int b_atypicalantipsy,int b_corticosteroids,int b_impotence2,int b_migraine,int b_ra,int b_renal,int b_semi,int b_sle,int b_treatedhyp,int b_type1,int b_type2,double bmi,int ethrisk,int fh_cvd,double rati,double sbp,double sbps5,int smoke_cat,int surv,double town
		)
		{
			double[] survivor = {
				0,
				0.998144447803497,
				0.996237337589264,
				0.994251489639282,
				0.992109060287476,
				0.989799082279205,
				0.987520277500153,
				0.985157012939453,
				0.982682824134827,
				0.979980647563934,
				0.977268040180206,
				0.974408507347107,
				0.971318483352661,
				0.968090057373047,
				0.964654147624969,
				0.960963070392609
			};

			/* The conditional arrays */

			double[] Iethrisk = {
				0,
				0,
				0.2771924876030827900000000,
				0.4744636071493126800000000,
				0.5296172991968937100000000,
				0.0351001591862990170000000,
				-0.3580789966932791900000000,
				-0.4005648523216514000000000,
				-0.4152279288983017300000000,
				-0.2632134813474996700000000
			};
			double[] Ismoke = {
				0,
				0.1912822286338898300000000,
				0.5524158819264555200000000,
				0.6383505302750607200000000,
				0.7898381988185801900000000
			};

			/* Applying the fractional polynomial transforms */
			/* (which includes scaling)                      */

			double dage = age;
			dage=dage/10;
			double age_1 = Math.Pow(dage,-1);
			double age_2 = Math.Pow(dage,3);
			double dbmi = bmi;
			dbmi=dbmi/10;
			double bmi_1 = Math.Pow(dbmi,-2);
			double bmi_2 = Math.Pow(dbmi,-2)*Math.Log(dbmi);

			/* The normalisation coefficients */

			double mage_1 = 0.234766781330109;
			double mage_2 = 77.284080505371094;
			double mbmi_1 = 0.149176135659218;
			double mbmi_2 = 0.141913309693336;
			double mrati = 4.300998687744141;
			double msbp = 128.571578979492190;
			double msbps5 = 8.756621360778809;
			double mtown = 0.526304900646210;

			/* Centring the continuous variables */

			age_1 = age_1 - mage_1;
			age_2 = age_2 - mage_2;
			bmi_1 = bmi_1 - mbmi_1;
			bmi_2 = bmi_2 - mbmi_2;
			rati = rati - mrati;
			sbp = sbp - msbp;
			sbps5 = sbps5 - msbps5;
			town = town - mtown;

			/* Start of Sum */
			double a=0;

			/* The conditional sums */

			a += Iethrisk[ethrisk];
			a += Ismoke[smoke_cat];

			/* The continuous coefficients */

			double cage_1 = -17.8397816660055750000000000;
			double cage_2 = 0.0022964880605765492000000;
			double cbmi_1 = 2.4562776660536358000000000;
			double cbmi_2 = -8.3011122314711354000000000;
			double crati = 0.1734019685632711100000000;
			double csbp = 0.0129101265425533050000000;
			double csbps5 = 0.0102519142912904560000000;
			double ctown = 0.0332682012772872950000000;

			/* Sum from continuous values */

			a += age_1 * cage_1;
			a += age_2 * cage_2;
			a += bmi_1 * cbmi_1;
			a += bmi_2 * cbmi_2;
			a += rati * crati;
			a += sbp * csbp;
			a += sbps5 * csbps5;
			a += town * ctown;

			/* The boolean coefficients */

			double cb_AF = 0.8820923692805465700000000;
			double cb_atypicalantipsy = 0.1304687985517351300000000;
			double cb_corticosteroids = 0.4548539975044554300000000;
			double cb_impotence2 = 0.2225185908670538300000000;
			double cb_migraine = 0.2558417807415991300000000;
			double cb_ra = 0.2097065801395656700000000;
			double cb_renal = 0.7185326128827438400000000;
			double cb_semi = 0.1213303988204716400000000;
			double cb_sle = 0.4401572174457522000000000;
			double cb_treatedhyp = 0.5165987108269547400000000;
			double cb_type1 = 1.2343425521675175000000000;
			double cb_type2 = 0.8594207143093222100000000;
			double cfh_cvd = 0.5405546900939015600000000;

			/* Sum from boolean values */

			a += b_AF * cb_AF;
			a += b_atypicalantipsy * cb_atypicalantipsy;
			a += b_corticosteroids * cb_corticosteroids;
			a += b_impotence2 * cb_impotence2;
			a += b_migraine * cb_migraine;
			a += b_ra * cb_ra;
			a += b_renal * cb_renal;
			a += b_semi * cb_semi;
			a += b_sle * cb_sle;
			a += b_treatedhyp * cb_treatedhyp;
			a += b_type1 * cb_type1;
			a += b_type2 * cb_type2;
			a += fh_cvd * cfh_cvd;

			/* The interaction coefficients */

			double cage_1_Ismoke1 = -0.2101113393351634600000000;
			double cage_1_Ismoke2 = 0.7526867644750319100000000;
			double cage_1_Ismoke3 = 0.9931588755640579100000000;
			double cage_1_Ismoke4 = 2.1331163414389076000000000;
			double cage_1_b_AF = 3.4896675530623207000000000;
			double cage_1_b_corticosteroids = 1.1708133653489108000000000;
			double cage_1_b_impotence2 = -1.5064009857454310000000000;
			double cage_1_b_migraine = 2.3491159871402441000000000;
			double cage_1_b_renal = -0.5065671632722369400000000;
			double cage_1_b_treatedhyp = 6.5114581098532671000000000;
			double cage_1_b_type1 = 5.3379864878006531000000000;
			double cage_1_b_type2 = 3.6461817406221311000000000;
			double cage_1_bmi_1 = 31.0049529560338860000000000;
			double cage_1_bmi_2 = -111.2915718439164300000000000;
			double cage_1_fh_cvd = 2.7808628508531887000000000;
			double cage_1_sbp = 0.0188585244698658530000000;
			double cage_1_town = -0.1007554870063731000000000;
			double cage_2_Ismoke1 = -0.0004985487027532612100000;
			double cage_2_Ismoke2 = -0.0007987563331738541400000;
			double cage_2_Ismoke3 = -0.0008370618426625129600000;
			double cage_2_Ismoke4 = -0.0007840031915563728900000;
			double cage_2_b_AF = -0.0003499560834063604900000;
			double cage_2_b_corticosteroids = -0.0002496045095297166000000;
			double cage_2_b_impotence2 = -0.0011058218441227373000000;
			double cage_2_b_migraine = 0.0001989644604147863100000;
			double cage_2_b_renal = -0.0018325930166498813000000;
			double cage_2_b_treatedhyp = 0.0006383805310416501300000;
			double cage_2_b_type1 = 0.0006409780808752897000000;
			double cage_2_b_type2 = -0.0002469569558886831500000;
			double cage_2_bmi_1 = 0.0050380102356322029000000;
			double cage_2_bmi_2 = -0.0130744830025243190000000;
			double cage_2_fh_cvd = -0.0002479180990739603700000;
			double cage_2_sbp = -0.0000127187419158845700000;
			double cage_2_town = -0.0000932996423232728880000;

			/* Sum from interaction terms */

			a += age_1 * Utilities.boolToInt((smoke_cat==1)) * cage_1_Ismoke1;
			a += age_1 * Utilities.boolToInt((smoke_cat==2)) * cage_1_Ismoke2;
			a += age_1 * Utilities.boolToInt((smoke_cat==3)) * cage_1_Ismoke3;
			a += age_1 * Utilities.boolToInt((smoke_cat==4)) * cage_1_Ismoke4;
			a += age_1 * b_AF * cage_1_b_AF;
			a += age_1 * b_corticosteroids * cage_1_b_corticosteroids;
			a += age_1 * b_impotence2 * cage_1_b_impotence2;
			a += age_1 * b_migraine * cage_1_b_migraine;
			a += age_1 * b_renal * cage_1_b_renal;
			a += age_1* b_treatedhyp * cage_1_b_treatedhyp;
			a += age_1 * b_type1 * cage_1_b_type1;
			a += age_1 * b_type2 * cage_1_b_type2;
			a += age_1 * bmi_1 * cage_1_bmi_1;
			a += age_1 * bmi_2 * cage_1_bmi_2;
			a += age_1 * fh_cvd * cage_1_fh_cvd;
			a += age_1 * sbp * cage_1_sbp;
			a += age_1 * town * cage_1_town;
			a += age_2 * Utilities.boolToInt((smoke_cat==1)) * cage_2_Ismoke1;
			a += age_2 * Utilities.boolToInt((smoke_cat==2)) * cage_2_Ismoke2;
			a += age_2 * Utilities.boolToInt((smoke_cat==3)) * cage_2_Ismoke3;
			a += age_2 * Utilities.boolToInt((smoke_cat==4)) * cage_2_Ismoke4;
			a += age_2 * b_AF * cage_2_b_AF;
			a += age_2 * b_corticosteroids * cage_2_b_corticosteroids;
			a += age_2 * b_impotence2 * cage_2_b_impotence2;
			a += age_2 * b_migraine * cage_2_b_migraine;
			a += age_2 * b_renal * cage_2_b_renal;
			a += age_2* b_treatedhyp * cage_2_b_treatedhyp;
			a += age_2 * b_type1 * cage_2_b_type1;
			a += age_2 * b_type2 * cage_2_b_type2;
			a += age_2 * bmi_1 * cage_2_bmi_1;
			a += age_2 * bmi_2 * cage_2_bmi_2;
			a += age_2 * fh_cvd * cage_2_fh_cvd;
			a += age_2 * sbp * cage_2_sbp;
			a += age_2 * town * cage_2_town;

			/* Calculate the score itself */
			double score = 100.0 * (1 - Math.Pow(survivor[surv], Math.Exp(a)) );
			return score;
		}

		static public Double cvd_male(
			int age,bool b_AF,bool b_atypicalantipsy,bool b_corticosteroids,bool b_impotence2,bool b_migraine,bool b_ra,bool b_renal,bool b_semi,bool b_sle,bool b_treatedhyp,DiabetesCat diabetes_cat,double bmi,Ethnicity ethnicity,bool fh_cvd,double rati,double sbp,double sbps5,SmokeCat smoke_cat,int surv,double town
		)
		{
			Double score;
			double tmp = cvd_male_raw(
				age,	// age must lie in range (25 .. 84)
				Utilities.boolToInt(b_AF),
				Utilities.boolToInt(b_atypicalantipsy),
				Utilities.boolToInt(b_corticosteroids),
				Utilities.boolToInt(b_impotence2),
				Utilities.boolToInt(b_migraine),
				Utilities.boolToInt(b_ra),
				Utilities.boolToInt(b_renal),
				Utilities.boolToInt(b_semi),
				Utilities.boolToInt(b_sle),
				Utilities.boolToInt(b_treatedhyp),
				Utilities.diabetescatToType1(diabetes_cat),
				Utilities.diabetescatToType2(diabetes_cat),
				bmi,	// bmi must lie in range (18 .. 47)
				Utilities.ethnicityToEthrisk(ethnicity),
				Utilities.boolToInt(fh_cvd),
				rati,	// rati must lie in range (1 .. 12)
				sbp,	// sbp must lie in range (70 .. 250)
				sbps5,	// sbps5 must lie in range (0 .. 40)
				Utilities.smokecatToInt(smoke_cat),
				surv,	// surv must lie in range (1 .. 10)
				town	// town must lie in range (-8 .. 11)
			);
			tmp = Math.Round(tmp*1000000.0)/1000000.0;
			score = tmp;

			return score;
		}

		/* End of cvd */

	}
}
