//
// (c) 2010 ClinRisk Ltd.
// All rights reserved.
//
// No unauthorised copying, distribution, modification, creating derived works, 
// or even compilation allowed, unless express permission has been granted by 
// ClinRisk Ltd.
//

using System;
using System.Collections.Generic;
using System.Text;

using CRStandardDefinitions;
using ClinRiskAutogenerated;

namespace sbpPredictor
{
    public class SbpPredictor
    {
        public static SbpPredictorResults estimate(Gender sex, int age, bool b_cvd, bool b_treatedhyp, DiabetesCat diabetes_cat, Ethnicity ethnicity, SmokeCat smoke_cat)
        {
            SbpPredictorResults results = new SbpPredictorResults();
            double score;
            if (sex == Gender.Female)
            {
                score = z3_sbp_predictor_0_2013.sbp_female(age, b_cvd, b_treatedhyp, diabetes_cat, ethnicity, smoke_cat);
            }
            else
            {
                score = z3_sbp_predictor_1_2013.sbp_male(age, b_cvd, b_treatedhyp, diabetes_cat, ethnicity, smoke_cat);
            }
            results.sbp = ((int)(score * 10 + 0.5)) / 10.0;
            return results;
        }


        public static String version()
        {
            return "sbpPredictor v. 2013.0";
        }

    }
}
