/* 
 * (c) 2013 ClinRisk Ltd.  All rights reserved.
 * This file has been auto-generated.
 * XML source: z3_ratio_predictor_1_2013.xml
 * STATA dta time stamp: 6 Nov 2012 10:19
 * .NET file create date: Sat 16 Mar 2013 14:51:30 GMT
 */

using System;
using CRStandardDefinitions;

namespace ClinRiskAutogenerated 
{
	public class z3_ratio_predictor_1_2013 {
		/* ratio */

		static private double ratio_male_raw(
			int age,int b_cvd,int b_treatedhyp,int b_type1,int b_type2,int ethrisk,int smoke_cat
		)
		{

			/* The conditional arrays */

			double[] Iethrisk = {
				0,
				0,
				0.0643572822217972910000000,
				0.3196714654045574300000000,
				0.3728164206457861300000000,
				0.1383706562007921400000000,
				-0.3108574725391891100000000,
				-0.3089106640468786700000000,
				-0.2099722774489782600000000,
				-0.1152440081257215700000000
			};
			double[] Ismoke = {
				0,
				0.0206486286827326890000000,
				0.0369765014954393230000000,
				0.1170645065311651900000000,
				0.1960188118531307500000000
			};

			/* Applying the fractional polynomial transforms */
			/* (which includes scaling)                      */

			double dage = age;
			dage=dage/10;
			double age_1 = Math.Pow(dage,.5);
			double age_2 = Math.Pow(dage,.5)*Math.Log(dage);

			/* The normalisation coefficients */

			double mage_1 = 2.279980897903442;
			double mage_2 = 3.758170127868652;

			/* Centring the continuous variables */

			age_1 = age_1 - mage_1;
			age_2 = age_2 - mage_2;

			/* Start of Sum */
			double a=0;

			/* The conditional sums */

			a += Iethrisk[ethrisk];
			a += Ismoke[smoke_cat];

			/* The continuous coefficients */

			double cage_1 = 4.5580218827601859000000000;
			double cage_2 = -1.4584913822560379000000000;

			/* Sum from continuous values */

			a += age_1 * cage_1;
			a += age_2 * cage_2;

			/* The boolean coefficients */

			double cb_cvd = -0.2777308881520427800000000;
			double cb_treatedhyp = -0.1095609032107525000000000;
			double cb_type1 = -0.8492995559645271100000000;
			double cb_type2 = -0.1179573046581720400000000;

			/* Sum from boolean values */

			a += b_cvd * cb_cvd;
			a += b_treatedhyp * cb_treatedhyp;
			a += b_type1 * cb_type1;
			a += b_type2 * cb_type2;

			/* The interaction coefficients */


			/* Sum from interaction terms */


			/* Calculate the score itself */
			double constant =  4.2933594349988526000000000;
			double score = a + constant;
			return score;
		}

		static public Double ratio_male(
			int age,bool b_cvd,bool b_treatedhyp,DiabetesCat diabetes_cat,Ethnicity ethnicity,SmokeCat smoke_cat
		)
		{
            // put age within allowed bounds
            if (age < 25)
                age = 25;
            if (age > 99)
                age = 99;
            Double score;
			double tmp = ratio_male_raw(
				age,	// age must lie in range (25 .. 99)
				Utilities.boolToInt(b_cvd),
				Utilities.boolToInt(b_treatedhyp),
				Utilities.diabetescatToType1(diabetes_cat),
				Utilities.diabetescatToType2(diabetes_cat),
				Utilities.ethnicityToEthrisk(ethnicity),
				Utilities.smokecatToInt(smoke_cat)
			);
			tmp = Math.Round(tmp*1000000.0)/1000000.0;
			score = tmp;

			return score;
		}

		/* End of ratio */

	}
}
