/* 
 * (c) 2013 ClinRisk Ltd.  All rights reserved.
 * This file has been auto-generated.
 * XML source: z3_sbp_predictor_1_2013.xml
 * STATA dta time stamp: 6 Nov 2012 10:19
 * .NET file create date: Sat 16 Mar 2013 14:52:45 GMT
 */

using System;
using CRStandardDefinitions;

namespace ClinRiskAutogenerated 
{
	public class z3_sbp_predictor_1_2013 {
		/* sbp */

		static private double sbp_male_raw(
			int age,int b_cvd,int b_treatedhyp,int b_type1,int b_type2,int ethrisk,int smoke_cat
		)
		{

			/* The conditional arrays */

			double[] Iethrisk = {
				0,
				0,
				-2.5145327622283427000000000,
				-3.4374836013645158000000000,
				-5.4690593711297932000000000,
				-3.7216793909309138000000000,
				-0.2869418742900070600000000,
				-0.2754209707578060800000000,
				-5.6678070021887672000000000,
				-2.0077980162008013000000000
			};
			double[] Ismoke = {
				0,
				0.1414961519427989600000000,
				-0.5772981857118055800000000,
				-0.1170206547474651200000000,
				0.7313641700162048000000000
			};

			/* Applying the fractional polynomial transforms */
			/* (which includes scaling)                      */

			double dage = age;
			dage=dage/10;
			double age_1 = Math.Pow(dage,3);
			double age_2 = Math.Pow(dage,3)*Math.Log(dage);

			/* The normalisation coefficients */

			double mage_1 = 140.471176147460940;
			double mage_2 = 231.543426513671870;

			/* Centring the continuous variables */

			age_1 = age_1 - mage_1;
			age_2 = age_2 - mage_2;

			/* Start of Sum */
			double a=0;

			/* The conditional sums */

			a += Iethrisk[ethrisk];
			a += Ismoke[smoke_cat];

			/* The continuous coefficients */

			double cage_1 = 0.1872822916339649000000000;
			double cage_2 = -0.0786647257369003930000000;

			/* Sum from continuous values */

			a += age_1 * cage_1;
			a += age_2 * cage_2;

			/* The boolean coefficients */

			double cb_cvd = -4.5775563014716374000000000;
			double cb_treatedhyp = 5.0805376278651329000000000;
			double cb_type1 = -0.3234544740702628400000000;
			double cb_type2 = -0.8334455114407504100000000;

			/* Sum from boolean values */

			a += b_cvd * cb_cvd;
			a += b_treatedhyp * cb_treatedhyp;
			a += b_type1 * cb_type1;
			a += b_type2 * cb_type2;

			/* The interaction coefficients */


			/* Sum from interaction terms */


			/* Calculate the score itself */
			double constant =  132.0303764215647100000000000;
			double score = a + constant;
			return score;
		}

		static public Double sbp_male(
			int age,bool b_cvd,bool b_treatedhyp,DiabetesCat diabetes_cat,Ethnicity ethnicity,SmokeCat smoke_cat
		)
		{
			Double score;
			double tmp = sbp_male_raw(
				age,	// age must lie in range (25 .. 99)
				Utilities.boolToInt(b_cvd),
				Utilities.boolToInt(b_treatedhyp),
				Utilities.diabetescatToType1(diabetes_cat),
				Utilities.diabetescatToType2(diabetes_cat),
				Utilities.ethnicityToEthrisk(ethnicity),
				Utilities.smokecatToInt(smoke_cat)
			);
			tmp = Math.Round(tmp*1000000.0)/1000000.0;
			score = tmp;

			return score;
		}

		/* End of sbp */

	}
}
