/* 
 * (c) 2013 ClinRisk Ltd.  All rights reserved.
 * This file has been auto-generated.
 * XML source: z3_sbp_predictor_0_2013.xml
 * STATA dta time stamp: 6 Nov 2012 10:19
 * .NET file create date: Sat 16 Mar 2013 14:52:40 GMT
 */

using System;
using CRStandardDefinitions;

namespace ClinRiskAutogenerated 
{
	public class z3_sbp_predictor_0_2013 {
		/* sbp */

		static private double sbp_female_raw(
			int age,int b_cvd,int b_treatedhyp,int b_type1,int b_type2,int ethrisk,int smoke_cat
		)
		{

			/* The conditional arrays */

			double[] Iethrisk = {
				0,
				0,
				-2.9244679967049616000000000,
				-3.1213363896979414000000000,
				-3.8336936844583591000000000,
				-3.6925193379027306000000000,
				1.2212998049577590000000000,
				0.5259807836784279300000000,
				-5.9292314207386889000000000,
				-1.5121876916771020000000000
			};
			double[] Ismoke = {
				0,
				-0.3829021287185129800000000,
				-0.5396575663643076200000000,
				0.4971535782680483500000000,
				1.0559421905145829000000000
			};

			/* Applying the fractional polynomial transforms */
			/* (which includes scaling)                      */

			double dage = age;
			dage=dage/10;
			double age_1 = Math.Pow(dage,3);
			double age_2 = Math.Pow(dage,3)*Math.Log(dage);

			/* The normalisation coefficients */

			double mage_1 = 154.101745605468750;
			double mage_2 = 258.768310546875000;

			/* Centring the continuous variables */

			age_1 = age_1 - mage_1;
			age_2 = age_2 - mage_2;

			/* Start of Sum */
			double a=0;

			/* The conditional sums */

			a += Iethrisk[ethrisk];
			a += Ismoke[smoke_cat];

			/* The continuous coefficients */

			double cage_1 = 0.3373357219028060800000000;
			double cage_2 = -0.1378414206389272100000000;

			/* Sum from continuous values */

			a += age_1 * cage_1;
			a += age_2 * cage_2;

			/* The boolean coefficients */

			double cb_cvd = -3.1391410460337048000000000;
			double cb_treatedhyp = 5.8044795979959956000000000;
			double cb_type1 = 3.3164395675234255000000000;
			double cb_type2 = -0.1895842103432965300000000;

			/* Sum from boolean values */

			a += b_cvd * cb_cvd;
			a += b_treatedhyp * cb_treatedhyp;
			a += b_type1 * cb_type1;
			a += b_type2 * cb_type2;

			/* The interaction coefficients */


			/* Sum from interaction terms */


			/* Calculate the score itself */
			double constant =  127.5984876378419300000000000;
			double score = a + constant;
			return score;
		}

		static public Double sbp_female(
			int age,bool b_cvd,bool b_treatedhyp,DiabetesCat diabetes_cat,Ethnicity ethnicity,SmokeCat smoke_cat
		)
		{
			Double score;
			double tmp = sbp_female_raw(
				age,	// age must lie in range (25 .. 99)
				Utilities.boolToInt(b_cvd),
				Utilities.boolToInt(b_treatedhyp),
				Utilities.diabetescatToType1(diabetes_cat),
				Utilities.diabetescatToType2(diabetes_cat),
				Utilities.ethnicityToEthrisk(ethnicity),
				Utilities.smokecatToInt(smoke_cat)
			);
			tmp = Math.Round(tmp*1000000.0)/1000000.0;
			score = tmp;

			return score;
		}

		/* End of sbp */

	}
}
